spring:
  profiles:
    active:
    - local
---

spring:
  profiles:
  - local
       
  mvc:
    view:
      prefix: "/WEB-INF/views"
      suffix: ".jsp"
  datasource:
    url: jdbc:mariadb://localhost:3306/bgg?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: gukgang
    driver-class-name: org.mariadb.jdbc.Driver
    
  session:
    jdbc:
      initialize-schema: always

server:
  port: 80
  
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
   
    jsp:
      init-parameters:
        development: true  
    session:
      timeout: 7200

  error:
    whitelabel:
      enabled: false
mybatis:
 type-aliases-package: com.lcomputerstudy.example.domain
 mapper-locations: mapper/**/*.xml   
logging:
 config: classpath:logback-spring.xml

